// enterprise-bundle/packages/angular-cli/src/app/app.component.ts
import { Component } from '@angular/core';
import { AgGridAngular } from 'ag-grid-angular';
import { ColDef, themeQuartz } from 'ag-grid-community';

import {
  AllEnterpriseModule,
  LicenseManager,
  ModuleRegistry,
} from 'ag-grid-enterprise';
import { AgChartsEnterpriseModule } from 'ag-charts-enterprise';
ModuleRegistry.registerModules([
  AllEnterpriseModule.with(AgChartsEnterpriseModule),
]);
LicenseManager.setLicenseKey('<your license key>');

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AgGridAngular],
  template: /*html*/ ` <ag-grid-angular
    style="height: 100%;"
    [theme]="theme"
    [rowData]="rowData"
    [columnDefs]="colDefs"
    [defaultColDef]="defaultColDef"
    [statusBar]="statusBar"
    [enableCharts]="enableCharts"
    [cellSelection]="cellSelection"
    loadThemeGoogleFonts
  >
  </ag-grid-angular>`,
})
export class AppComponent {
  theme = themeQuartz;
  enableCharts = true;
  cellSelection = true;
  rowData = [
    { make: 'Toyota', model: 'Celica', price: 35000 },
    { make: 'Ford', model: 'Mondeo', price: 32000 },
    { make: 'Porsche', model: 'Boxster', price: 72000 },
  ];

  colDefs: ColDef[] = [
    { field: 'make' },
    { field: 'model' },
    { field: 'price' },
  ];

  defaultColDef = {
    flex: 1,
  };

  statusBar = {
    statusPanels: [
      {
        statusPanel: 'agTotalAndFilteredRowCountComponent',
        align: 'left',
      },
    ],
  };
}

<ag-grid-angular
  class="ag-theme-quartz"
  style="height: 100%;"
  [rowData]="rowData"
  [columnDefs]="colDefs"
  [defaultColDef]="defaultColDef"
  [statusBar]="statusBar">
</ag-grid-angular>

// enterprise-bundle/packages/create-react-app/src/App.js
import {useState} from 'react'

import {AgGridReact} from 'ag-grid-react'; // React Data Grid Component

import { AllEnterpriseModule, LicenseManager, ModuleRegistry, themeQuartz } from "ag-grid-enterprise";
import { AgChartsEnterpriseModule } from "ag-charts-enterprise";
ModuleRegistry.registerModules([AllEnterpriseModule.with(AgChartsEnterpriseModule)]);
LicenseManager.setLicenseKey("<your license key>")

function App() {
  const [rowData] = useState([
    {make: "Toyota", model: "Celica", price: 35000},
    {make: "Ford", model: "Mondeo", price: 32000},
    {make: "Porsche", model: "Boxster", price: 72000}
  ]);

  const [colDefs] = useState([
    {field: "make"},
    {field: "model"},
    {field: "price"}
  ]);

  const [defaultColDef] = useState({
    flex: 1,
  });

  const [statusBar] = useState({
    statusPanels: [
      {
        statusPanel: 'agTotalAndFilteredRowCountComponent',
        align: 'left',
      }
    ]
  });

  return (
      <>
        <div
            className="ag-theme-quartz" // applying the grid theme
            style={{height: "100%", width: "100%"}} // the grid will fill the size of the parent container
        >
          <AgGridReact
              theme={themeQuartz}
              rowData={rowData}
              columnDefs={colDefs}
              defaultColDef={defaultColDef}
              statusBar={statusBar}
              enableCharts
              cellSelection
              loadThemeGoogleFonts
          />
        </div>
      </>
  )
}

export default App;
